### PR TITLE
(Some) Sounds of /vg/station13

### PR DESCRIPTION
**Pull request by Inorien**
## Lobby Music
- All /vg/station13 lobby musics (base has some shit ones, remove as the community rees about them)

## AI Sounds Replaced

- Aliens ("Unidentified lifesigns detected...")
- Meteors ("Meteors have been detected on collision course...")
- Radiation ("High levels of radiation...")
- Intercept ("Attention, enemy communication intercepted...")
- Level 7 Outbreak (base only has level 7, created equivalent from our files)
- announce.ogg (sounds like some airport chime) replaced with _bloop.wav re-encoded to .ogg

## Effects Replaced

- All male screams
- All female screams

## Added
- Smelelele as a RoundEnd sound but it plays when the whole thing ends (like apc destroyed mission accomplished) for now

## Why it's good
home

## How it was tested
it wasn't lmao

**Changelog**
- add: Lobby music from /vg/station13
- add: SMELELELELELELELE
- tweak: Replaced some AI, human scream sounds with those from /vg/station13

### CODE REVIEW

**Comment by Eneocho** [comment]
does this add the "in 1990 nine-cha-cha analfisting, in 1990s-" sound effect

**Comment by Inorien** [comment]
> does this add the "in 1990 nine-cha-cha analfisting, in 1990s-" sound effect

it does not, i'll find it

**Comment by Inorien** [comment]
base does not have an existing file for this as malf itself doesnt exist, rather than copying over files that won't be used will leave it for when malf is ported

**Comment by Inorien** [comment]
oops looks like i fucked up the prototype

**Comment by Inorien** [comment]
i dunno why in the fuck `TryStopNukeOpsFromConstantlyFailing` is failing but i'll get to it tomorrow

**Comment by west3436** [comment]
> i dunno why in the fuck `TryStopNukeOpsFromConstantlyFailing` is failing but i'll get to it tomorrow

Passing now so who knows lmao

**Pull request merged**
